### ISSUE TITLE
Private messaging

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#138]
- [ ] Add a "Private message" button on user profiles, leading to creating a post with special type "pm".
- [ ] Creating a PM adds a "read" user_role to the recipents
- [ ] Have a PM section of the dashboard listing both received and sent PMs (though maybe only the titles). Also with a button to create a PM from scratch.
- [ ] PMs work like blog posts, except with a special header listing the people involved
- [ ] Include PMs in notifications
- [ ] Make sure only granted users can read PMs

Bonus: letting the PM sender dynamically add/remove recipients (making it almost an asynchronous chat system for teams actually)

Bonus: actually send emails (opt-in)

**Comment by mkalam-alami** [comment]
Moved to the [Feature requests](https://github.com/alakajam-team/alakajam/wiki/Feature-requests) page for now.
