### ISSUE TITLE
Deal with content deletion properly

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#254]
### High priority

- [x] Let people delete their accounts
- [ ] Soft deletion with most models, or at least deletion activity traces 

### Medium priority

- [ ] When comments get deleted, if they are not last, have a placeholder "[deleted]" thing instead
- [x] Don't update entry counts when entry submissions are closed

### Longer term

- [ ] Setup a cron system (with the matching admin page)
- [ ] Make sure accounts are only deleted after a cetain delay, thanks to a cron task. User account + contents are blanked after that so we effectively no longer have any user info.
- [ ] Deleted pictures go in a trash, then are pruned after X days

**Comment by mkalam-alami** [comment]
> another feature could be a time delay on user requested account deletion

**Comment by mkalam-alami** [comment]
Moved to the [Feature requests](https://github.com/alakajam-team/alakajam/wiki/Feature-requests) page for now.
