### ISSUE TITLE
Improved front page experience

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#488]
> Objectives:
> 1. A cleaner, more "pro" and readable layout  
> 2. A bigger sense of activity ("join" counter, more types of activities like new comments in the feed)   
> 3. A more compact jumbotron to make more room for community contents  
>  
> In the long run, the aim is an overall smoother experience for newcomers, from learning about the event to deciding to join to taking part in each phase of the jam. The front page is the first part of that - for the following steps I'm considering reworked headers (global: #489, events: #343), possibly a full "my event participation" page (#460, related: #209), and email notifications (#375). Related discussion: #434

**Front page layout and activity**

- [x] Implement the overall layout using this mockup as the starting point: https://alakajam-team.github.io/alakajam-tools/
- [x] Add latest comments to the activity feed
- [ ] Add latest high scores to the activity feed
- [ ] Add new users to the activity feed
- [ ] *(Bonus)* Make the feed more clever by having "grouped" variations of activities (eg. "5 high scores were submitted to game X")
- [ ] Rework blog post presentation to match the mock (get rid of the "expand" button, just let people open posts to read them)
- [ ] Have a good variant of the front page for logged out users (migrate the "New website unlocked" block and possibly improve it, replace all the sidebar of the jumbotron with info relevant to newcomers)
- [ ] *(Bonus)* Show the Twitter feed somewhere, maybe below the latest activities.

**New features**

- [x] Ability to "join" an event / Join counter (#461)
- [x] Add settings for streamers to appear in the front page (#476 #466)

**Comment by ttencate** [comment]
Good ideas in general. But it occurs to me that the front page serves many masters: newcomers as well as event participants. Newcomers should be explained what AKJ is and encouraged in all possible ways to participate; existing participants will more likely want to see community activity and have convenient links to their own stuff.

So maybe we can change the front page drastically depending on whether someone's logged in or not? Several big sites do this; GitHub is a good example.

**Comment by mkalam-alami** [comment]
👍 We can at least rethink the event-related jumbotron for anonymous users. Just added a new bullet point to the list

**Comment by mkalam-alami** [comment]
Remaining stuff before deploying a first version:

- [ ] Fix Bookshelf code broken after lint upgrade
- [ ] Verify CI passes

**Comment by mkalam-alami** [comment]
The main objectives of the issue have been attained, remaining tasks are less of a priority. Closing.
