### ISSUE TITLE
Support special hand-picked podiums

### ISSUE THREAD

**Issue by mkalam-alami** [alakajam-team/alakajam#517]
In order to support ScoreSpace's "Developer's Choice"/"Streamer's Choice"/"ScoreSpace Choice"

### TODO-list

- [x] Add support for a 7th rating category
- [x] Create an event administration page to edit manually the rankings of any category (= simply set rankings as values for now)
- [x] Add "ScoreSpace awards" flag to events. Put a description below explaining how to map 7th category rankings to awards
- [x] Make the flag enable a special podium on the results page with hard-coded award names, referencing the 7th rating category

Bonus: Have built-in support for "jury-based rating categories", ie. they don't show up on the ratings phase.
